---

- name: Modify nproc limit for OpenVPN service
  lineinfile:
    path: /lib/systemd/system/openvpn@.service
    regexp: '^LimitNPROC='
    line: LimitNPROC=infinity

- name: Copy configs for each client
  copy:
    src: "{{ openvpn_etcdir }}/server.conf"
    dest: "{{ openvpn_etcdir }}/{{ item }}.conf"
    force: yes
    remote_src: yes
  with_items: "{{ openvpn_clients }}"

  # - name: Modify execstart for OpenVPN service
  #   lineinfile:
  #     path: /lib/systemd/system/openvpn@.service
  #     regexp: '^ExecStart='
  #     line: /usr/sbin/openvpn --daemon ovpn-%i --status /run/openvpn/%i.status 10 --cd /etc/openvpn --config /etc/openvpn/%i.conf --writepid /run/openvpn/%i.pid

- name: Ensure OpenVPN is started
  service:
    name: "{{ openvpn_service }}"
    state: started
    enabled: true
